#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}

if [[ ${SOURCE_IMAGE} == 'asan' ]]; then
    SOURCE_IMAGE='centos:7'
fi

if [[ ${WITH_AZURITE} == "ON" ]]; then
    if [[ $(docker network list | grep bridge-azurite) != *bridge-azurite* ]]; then
        docker network create bridge-azurite
    fi
    docker run -d -p 10000:10000 -p 10001:10001 --name azurite --network bridge-azurite mcr.microsoft.com/azure-storage/azurite:3.14.0

    AZURITE_DOCKER_FLAG="--network bridge-azurite"
fi

if [[ ${WITH_XBCLOUD_TESTS} == "true" ]]; then
    docker run -d --security-opt seccomp=unconfined --cap-add=NET_ADMIN --rm -p 9000:9000 --rm -p 9001:9001 --name s3 altmannmarcelo/minio:latest

    XBCLOUD_CREDENTIALS="--storage=s3 --s3-endpoint='http://127.0.0.1:9000' --s3-access-key=admin --s3-secret-key=password --s3-bucket=newbucket"
fi

if [[ ${WITH_VAULT_TESTS} == "true" ]]; then
    docker run -d --security-opt seccomp=unconfined --cap-add=NET_ADMIN --rm -p 8200:8200 --name vault altmannmarcelo/vault:latest
    docker cp vault:/opt/vault/tls/tls.crt $ROOT_DIR/vault.crt
    sleep 10
    docker logs vault
    export TOKEN=$(docker logs vault | grep 'export VAULT_TOKEN' | awk -F'=' '{print $2}')
fi

if [[ ${WITH_KMIP_TESTS} == "true" ]]; then
    docker run -d --security-opt seccomp=unconfined --cap-add=NET_ADMIN --rm -p 5696:5696 --name kmip altmannmarcelo/kmip:latest

    docker cp kmip:/opt/certs/root_certificate.pem $ROOT_DIR
    docker cp kmip:/opt/certs/client_key_jane_doe.pem $ROOT_DIR
    docker cp kmip:/opt/certs/client_certificate_jane_doe.pem $ROOT_DIR
fi

XTRABACKUP_TARGET_VERSION=$(set | grep -i $XTRABACKUP_TARGET'_VERSION' | awk -F '=' '{print $2}')

docker run --rm \
    --security-opt seccomp=unconfined --net host \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/pxb \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    ${AZURITE_DOCKER_FLAG} \
    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace

    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export XBTR_ARGS='${XBTR_ARGS}'
    export XTRABACKUP_TARGET='${XTRABACKUP_TARGET}'
    export XTRABACKUP_TARGET_VERSION='${XTRABACKUP_TARGET_VERSION}'
    export BOOTSTRAP_URL='${BOOTSTRAP_URL}'
    export WITH_AZURITE='${WITH_AZURITE}'
    export LANG=en_AU.UTF-8
    export XBCLOUD_CREDENTIALS='${XBCLOUD_CREDENTIALS}'
    export VAULT_URL=https://127.0.0.1:8200
    export VAULT_CACERT=/tmp/pxb/vault.crt
    export VAULT_CA=/tmp/pxb/vault.crt
    export VAULT_TOKEN=${TOKEN}
    export KMIP_CLIENT_CA=/tmp/pxb/client_certificate_jane_doe.pem
    export KMIP_CLIENT_KEY=/tmp/pxb/client_key_jane_doe.pem
    export KMIP_SERVER_CA=/tmp/pxb/root_certificate.pem

    mkdir /tmp/results
    cp /tmp/pxb/results/*.tar.gz /tmp/results

    bash -x /tmp/scripts/test-binary /tmp/results

    sudo mv /tmp/results/*.xml /tmp/results/*.output /tmp/results/test_results.subunit /tmp/results/results/ /tmp/pxb/results/ || true
    sudo chown $(id -u):$(id -g) -R /tmp/pxb/results/
"
